### ISSUE TITLE
Please do not pin requests

### ISSUE THREAD

**Issue by jone** [tizz98/py-pspdfkit#6]
This package has a specific pinning for the exact version of `requests==2.18.4` in the `install_requires` in the `setup.py`.
Please do not pin an exact version, but use a version constraint (e.g. `requests>=2.18.4`).
It is a very bad habit to pin exact versions in `setup.py` because if two packages do that they cannot be installed at the same time.

**Comment by tizz98** [comment]
Pull requests are welcome :)

**Comment by r-kells** [comment]
Made a PR https://github.com/tizz98/py-pspdfkit/pull/8 @tizz98 @jone

**Comment by tizz98** [comment]
@jone @r-kells released as version `0.2.5` https://pypi.org/project/py-pspdfkit/0.2.5/
